# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pubsub.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pubsub.proto',
  package='spotify.hermes.pubsub.proto',
  serialized_pb='\n\x0cpubsub.proto\x12\x1bspotify.hermes.pubsub.proto\"@\n\x0cSubscription\x12\x0b\n\x03uri\x18\x01 \x01(\t\x12\x0e\n\x06\x65xpiry\x18\x02 \x01(\x05\x12\x13\n\x0bstatus_code\x18\x03 \x01(\x05')




_SUBSCRIPTION = _descriptor.Descriptor(
  name='Subscription',
  full_name='spotify.hermes.pubsub.proto.Subscription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uri', full_name='spotify.hermes.pubsub.proto.Subscription.uri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='expiry', full_name='spotify.hermes.pubsub.proto.Subscription.expiry', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status_code', full_name='spotify.hermes.pubsub.proto.Subscription.status_code', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=45,
  serialized_end=109,
)

DESCRIPTOR.message_types_by_name['Subscription'] = _SUBSCRIPTION

class Subscription(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SUBSCRIPTION

  # @@protoc_insertion_point(class_scope:spotify.hermes.pubsub.proto.Subscription)


# @@protoc_insertion_point(module_scope)
